name: Docker Image Varnish
on:
  schedule:
    - cron: "0 3 * * 0" # At 03:00 on Sunday
  push:
    branches:
      - 'main'
    paths:
      - version
      - images/varnish/**
      - .github/workflows/*varnish*

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix=${{ vars.VARNISH_MATRIX }}" >> $GITHUB_OUTPUT
      - run: echo "Matrix:\n";echo '${{ steps.set-matrix.outputs.matrix }}'

  varnish:
    needs: build-matrix
    name: Varnish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Determine Version
        run: |-
          ESCAPED_VERSION="$(echo ${{ matrix.version }} | sed 's/\./\\\./g')"
          VARNISH_VERSION=$(
            docker run --rm gcr.io/go-containerregistry/crane:v0.8.0 ls varnish \
            | egrep "^${ESCAPED_VERSION}(\.[0-9]+)?(\.[0-9]+)?(-alpine)?\$" | sort -Vr | head -n1
          )
          echo "VARNISH_VERSION=${VARNISH_VERSION}" | tee /dev/stderr >> $GITHUB_ENV

      - uses: docker/build-push-action@v3
        with:
          context: images/varnish
          platforms: linux/amd64,linux/arm64
          build-args: VARNISH_VERSION=${{ env.VARNISH_VERSION }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/varnish:${{ matrix.version }}

  varnish-lts:
    name: Varnish LTS
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - "6.0"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Determine Version
        run: |-
          ESCAPED_VERSION="$(echo ${{ matrix.version }} | sed 's/\./\\\./g')"
          VARNISH_VERSION=$(
            docker run --rm gcr.io/go-containerregistry/crane:v0.8.0 ls varnish \
            | egrep "^${ESCAPED_VERSION}(\.[0-9]+)?(\.[0-9]+)?(-alpine)?\$" | sort -Vr | head -n1
          )
          echo "VARNISH_VERSION=${VARNISH_VERSION}" | tee /dev/stderr >> $GITHUB_ENV

      - uses: docker/build-push-action@v3
        with:
          context: images/varnish
          file: images/varnish/Dockerfile.lts
          platforms: linux/amd64,linux/arm64
          build-args: VARNISH_VERSION=${{ env.VARNISH_VERSION }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/varnish:${{ matrix.version }}
