name: Docker Image Magento 1 PHP-FPM
on:
  schedule:
    - cron: "0 3 1 * *" # At 03:00 on day-of-month 1
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - version
      - images/php-fpm/magento1/**

jobs:
  call-matrix-generator:
    uses: ./.github/workflows/php-matrix-generator.yml

  magento1:
    name: Magento 1 PHP-FPM ${{ matrix.php_version }}
    runs-on: ${{ matrix.os }}
    needs: [ call-matrix-generator ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version == 'x' }}
        with:
          file: images/php-fpm/magento1/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-magento1

  magento1-node:
    name: Magento 1 PHP-FPM ${{ matrix.php_version }} + Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    needs: [ call-matrix-generator ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version != 'x' }}
        with:
          file: images/php-fpm/magento1/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}-node${{ matrix.node_version }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-node${{ matrix.node_version }}-magento1

  magento1-xdebug3:
    name: Magento 1 PHP-FPM ${{ matrix.php_version }} + XDebug 3
    runs-on: ${{ matrix.os }}
    needs: [ magento1 ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version == 'x' }}
        with:
          file: images/php-fpm/xdebug3/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}-magento1
            XDEBUG_TYPE=${{ matrix.xdebug_type }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-magento1-xdebug3

  magento1-xdebug3-node:
    name: Magento 1 PHP-FPM ${{ matrix.php_version }} + XDebug 3 + Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    needs: [ magento1, magento1-node ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version != 'x' }}
        with:
          file: images/php-fpm/xdebug3/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}-node${{ matrix.node_version }}-magento1
            XDEBUG_TYPE=${{ matrix.xdebug_type }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-node${{ matrix.node_version }}-magento1-xdebug3

  magento1-spx:
    name: Magento 1 PHP-FPM ${{ matrix.php_version }} + SPX
    runs-on: ${{ matrix.os }}
    needs: [ magento1 ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version == 'x' }}
        with:
          file: images/php-fpm/spx/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}-magento1
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-magento1-spx

  magento1-spx-node:
    name: Magento 1 PHP-FPM ${{ matrix.php_version }} + SPX + Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    needs: [ magento1, magento1-node ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version != 'x' }}
        with:
          file: images/php-fpm/spx/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}-node${{ matrix.node_version }}-magento1
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-node${{ matrix.node_version }}-magento1-spx

  magento1-blackfire:
    name: Magento 1 PHP-FPM ${{ matrix.php_version }} + Blackfire
    runs-on: ${{ matrix.os }}
    needs: [ magento1 ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version == 'x' }}
        with:
          file: images/php-fpm/blackfire/Dockerfile
          context: images/php-fpm/
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}-magento1
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-magento1-blackfire

  magento1-blackfire-node:
    name: Magento 1 PHP-FPM ${{ matrix.php_version }} + Blackfire + Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    needs: [ magento1, magento1-node ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version != 'x' }}
        with:
          file: images/php-fpm/blackfire/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}-node${{ matrix.node_version }}-magento1
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-node${{ matrix.node_version }}-magento1-blackfire
