name: Docker Image MySQL
on:
  schedule:
    - cron: "0 3 * * 0" # At 03:00 on Sunday
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - version
      - images/mysql/**

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix=${{ vars.MYSQL_MATRIX }}" >> $GITHUB_OUTPUT
      - run: echo "Matrix:\n";echo '${{ steps.set-matrix.outputs.matrix }}'

  mysql:
    needs: build-matrix
    name: MySQL
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Set build-args
        run: |-
          ESCAPED_VERSION="$(echo ${{ matrix.version }} | sed 's/\./\\\./g')"
          MYSQL_VERSION=$(
            curl -s curl -s https://hub.docker.com/v2/repositories/library/mysql/tags/?page_size=200 \
            | jq -r '.results[].name' \
            | egrep "^${ESCAPED_VERSION}(\.[0-9]+)?(\.[0-9]+)?(-oracle)?\$" | sort -Vr | head -n1
          )
          echo "MYSQL_VERSION=${MYSQL_VERSION}" | tee /dev/stderr >> $GITHUB_ENV

      - uses: docker/build-push-action@v6
        with:
          context: images/mysql
          platforms: linux/amd64,linux/arm64
          build-args: MYSQL_VERSION=${{ env.MYSQL_VERSION }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/mysql:${{ matrix.version }}

  delete-versions:
    name: Delete versions
    needs: [ mysql ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'mysql'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'

  update-readme:
    needs: [ mysql ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios

      - name: Update README.md
        run: node .github/workflows/actions/readme-update.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_NAME: MySQL

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update MySQL versions in README.md"
            git push
          else
            echo "No changes to commit"
          fi
