name: Docker Image Elasticsearch
on:
  schedule:
    - cron: "0 3 * * 0" # At 03:00 on Sunday
  push:
    paths:
      - images/version
      - images/elasticsearch/**
      - .github/workflows/*elasticsearch*

jobs:
  elasticsearch:
    name: Elasticsearch
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: ${{ vars.ELASTICSEARCH_VERSIONS }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Set build-args
        run: |-
          ESCAPED_VERSION="$(echo ${{ matrix.version }} | sed 's/\./\\\./g')"
          ES_VERSION=$(
            docker run --rm gcr.io/go-containerregistry/crane:v0.8.0 ls docker.elastic.co/elasticsearch/elasticsearch \
            | egrep "^${ESCAPED_VERSION}\.[0-9]+(\.[0-9]+)?\$" | sort -Vr | head -n1
          )
          echo "ES_VERSION=${ES_VERSION}" | tee /dev/stderr >> $GITHUB_ENV

      - uses: docker/build-push-action@v3
        with:
          context: images/elasticsearch
          platforms: linux/amd64,linux/arm64
          build-args: ES_VERSION=${{ env.ES_VERSION }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/elasticsearch:${{ matrix.version }}
