name: Docker Image Magento 2 PHP-FPM
on:
  schedule:
    - cron: "0 3 * * 0" # At 03:00 on Sunday
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - version
      - images/php-fpm/magento2/**

jobs:
  call-matrix-generator:
    uses: ./.github/workflows/php-matrix-generator.yml

  general-php-fpm:
    uses: ./.github/workflows/docker-image-general-php-fpm.yml
    secrets: inherit

  magento2:
    name: Magento 2 PHP-FPM ${{ matrix.php_version }}
    runs-on: ${{ matrix.os }}
    needs: [ call-matrix-generator, general-php-fpm ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version == 'x' }}
        with:
          file: images/php-fpm/magento2/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-magento2

  magento2-node:
    name: Magento 2 PHP-FPM ${{ matrix.php_version }} + Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    needs: [ call-matrix-generator, general-php-fpm ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version != 'x' }}
        with:
          file: images/php-fpm/magento2/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}-node${{ matrix.node_version }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-node${{ matrix.node_version }}-magento2

  magento2-xdebug3:
    name: Magento 2 PHP-FPM ${{ matrix.php_version }} + XDebug 3
    runs-on: ${{ matrix.os }}
    needs: [ magento2 ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version == 'x' }}
        with:
          file: images/php-fpm/xdebug3/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}-magento2
            XDEBUG_TYPE=${{ matrix.xdebug_type }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-magento2-xdebug3

  magento2-xdebug3-node:
    name: Magento 2 PHP-FPM ${{ matrix.php_version }} + XDebug 3 + Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    needs: [ magento2, magento2-node ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version != 'x' }}
        with:
          file: images/php-fpm/xdebug3/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}-node${{ matrix.node_version }}-magento2
            XDEBUG_TYPE=${{ matrix.xdebug_type }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-node${{ matrix.node_version }}-magento2-xdebug3

  magento2-spx:
    name: Magento 2 PHP-FPM ${{ matrix.php_version }} + SPX
    runs-on: ${{ matrix.os }}
    needs: [ magento2 ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version == 'x' }}
        with:
          file: images/php-fpm/spx/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}-magento2
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-magento2-spx

  magento2-spx-node:
    name: Magento 2 PHP-FPM ${{ matrix.php_version }} + SPX + Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    needs: [ magento2, magento2-node ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version != 'x' }}
        with:
          file: images/php-fpm/spx/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}-node${{ matrix.node_version }}-magento2
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-node${{ matrix.node_version }}-magento2-spx

  magento2-blackfire:
    name: Magento 2 PHP-FPM ${{ matrix.php_version }} + Blackfire
    runs-on: ${{ matrix.os }}
    needs: [ magento2 ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version == 'x' }}
        with:
          file: images/php-fpm/blackfire/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}-magento2
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-magento2-blackfire

  magento2-blackfire-node:
    name: Magento 2 PHP-FPM ${{ matrix.php_version }} + Blackfire + Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    needs: [ magento2, magento2-node ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version != 'x' }}
        with:
          file: images/php-fpm/blackfire/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}-node${{ matrix.node_version }}-magento2
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-node${{ matrix.node_version }}-magento2-blackfire

  delete-versions:
    name: Delete versions
    needs: [ magento2, magento2-node, magento2-xdebug3, magento2-xdebug3-node, magento2-spx, magento2-spx-node, magento2-blackfire, magento2-blackfire-node ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'php-fpm'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
