name: Docker Image OpenSearch
on:
  schedule:
    - cron: "0 3 1 * *" # At 03:00 on day-of-month 1
  push:
    branches:
      - 'main'
    paths:
      - version
      - images/opensearch/**
      - .github/workflows/*opensearch*

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          VERSIONS=$(curl -s 'https://registry.hub.docker.com/v2/repositories/opensearchproject/opensearch/tags?page_size=200' \
            | jq -r '.results[].name' \
            | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' \
            | sort -Vr \
            | head -n 3)
          LATEST_VERSIONS=$(echo "$VERSIONS" | awk -F. '{print $1"."$2}' | uniq | while read version; do echo "$VERSIONS" | grep "^$version" | head -n 1; done)
          MATRIX=$(jq -c -n --arg versions "$LATEST_VERSIONS" '{"version": ($versions | split("\n") | map(select(length > 0)))}')
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
      - run: echo "Matrix:\n${{ steps.set-matrix.outputs.matrix }}"

  opensearch:
    needs: build-matrix
    name: OpenSearch
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Set build-args
        run: |-
          ESCAPED_VERSION="$(echo ${{ matrix.version }} | sed 's/\./\\\./g')"
          OPENSEARCH_VERSION=$(
            curl -s curl -s https://registry.hub.docker.com/v2/repositories/opensearchproject/opensearch/tags?page_size=200 \
            | jq -r '.results[].name' \
            | egrep "^${ESCAPED_VERSION}\.[0-9]+(\.[0-9]+)?\$" | sort -Vr | head -n1
          )
          echo "OPENSEARCH_VERSION=${OPENSEARCH_VERSION}" | tee /dev/stderr >> $GITHUB_ENV

      - uses: docker/build-push-action@v6
        with:
          context: images/opensearch
          platforms: linux/amd64,linux/arm64
          build-args: OPENSEARCH_VERSION=${{ env.OPENSEARCH_VERSION }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/opensearch:${{ matrix.version }}

      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'opensearch'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
