name: Docker Image PHP-FPM
on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
  workflow_dispatch:

jobs:
  call-matrix-generator:
    uses: ./.github/workflows/php-matrix-generator.yml

  php-fpm:
    needs: [ call-matrix-generator ]
    name: PHP-FPM ${{ matrix.php_version }}
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.php-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        with:
          file: images/php-fpm/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
            ENV_SOURCE_IMAGE=public.ecr.aws/docker/library/php
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-buildcache,mode=max

  php-node:
    name: PHP-FPM ${{ matrix.php_version }} + Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    needs: [ php-fpm, call-matrix-generator ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 6 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.node-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        with:
          file: images/php-fpm/node/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}
            NODE_VERSION=${{ (matrix.php_version <= '7.4') && '20' || matrix.node_version }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-node${{ matrix.node_version }}

  xdebug3:
    name: PHP-FPM ${{ matrix.php_version }} + XDebug 3
    runs-on: ${{ matrix.os }}
    needs: [ php-node, call-matrix-generator ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version == 'x' }}
        with:
          file: images/php-fpm/xdebug3/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}
            XDEBUG_TYPE=${{ matrix.xdebug_type }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-xdebug3

  xdebug3-node:
    name: PHP-FPM ${{ matrix.php_version }} + XDebug 3 + Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    needs: [ php-node, call-matrix-generator ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version != 'x' }}
        with:
          file: images/php-fpm/xdebug3/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}-node${{ matrix.node_version }}
            XDEBUG_TYPE=${{ matrix.xdebug_type }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-node${{ matrix.node_version }}-xdebug3

  spx:
    name: PHP-FPM ${{ matrix.php_version }} + SPX
    runs-on: ${{ matrix.os }}
    needs: [ php-node, call-matrix-generator ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version == 'x' }}
        with:
          file: images/php-fpm/spx/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-spx

  spx-node:
    name: PHP-FPM ${{ matrix.php_version }} + SPX + Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    needs: [ php-node, call-matrix-generator ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version != 'x' }}
        with:
          file: images/php-fpm/spx/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}-node${{ matrix.node_version }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-node${{ matrix.node_version }}-spx

  blackfire:
    name: PHP-FPM ${{ matrix.php_version }} + Blackfire
    runs-on: ${{ matrix.os }}
    needs: [ php-node, call-matrix-generator ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version == 'x' }}
        with:
          file: images/php-fpm/blackfire/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-blackfire

  blackfire-node:
    name: PHP-FPM ${{ matrix.php_version }} + Blackfire + Node ${{ matrix.node_version }}
    runs-on: ${{ matrix.os }}
    needs: [ php-node, call-matrix-generator ]
    continue-on-error: false
    strategy:
      fail-fast: false
      max-parallel: ${{ github.ref == 'refs/heads/main' && 2 || 0 }}
      matrix: ${{ fromJson(needs.call-matrix-generator.outputs.full-matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        if: ${{ matrix.node_version != 'x' }}
        with:
          file: images/php-fpm/blackfire/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          build-args: |
            ENV_SOURCE_IMAGE=ghcr.io/${{ github.repository_owner }}/php-fpm
            PHP_VERSION=${{ matrix.php_version }}-node${{ matrix.node_version }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm:${{ matrix.php_version }}-node${{ matrix.node_version }}-blackfire
