name: Docker Image Nginx
on:
  schedule:
    - cron: "0 3 * * 0" # At 03:00 on Sunday
  push:
    branches:
      - 'main'
    paths:
      - version
      - images/nginx/**
      - .github/workflows/*nginx*

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix=${{ vars.NGINX_MATRIX }}" >> $GITHUB_OUTPUT
      - run: echo "Matrix:\n";echo '${{ steps.set-matrix.outputs.matrix }}'

  nginx:
    needs: build-matrix
    name: Nginx
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v6
        with:
          context: images/nginx
          platforms: linux/amd64,linux/arm64
          build-args: NGINX_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/main' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/nginx:${{ matrix.version }}

      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'nginx'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: 'true'
